default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tickets_development

test:
  <<: *default
  database: tickets_test

production:
  <<: *default
  database: tickets_production